import { motion } from "framer-motion";
import { AlertTriangle, Bot, Check, ExternalLink, FileText, Sparkles } from "lucide-react";
import type { ChatResponse, RankedCve, Source } from "../../types/chat";
import { CveCard } from "../cve/CveCard";
import { Badge } from "../ui/badge";
import { joinedList } from "../../utils/format";
function cell(value: unknown) { return value === undefined || value === null || value === "" ? "—" : String(value); }
function SourcesTable({ sources }: { sources: Source[] }) { return <div className="overflow-x-auto rounded-xl border border-border"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-slate-900/70 text-slate-400"><tr>{["CVE", "Vendor", "Product", "Severity", "CVSS", "Source", "Published", "Patch status"].map(x => <th key={x} className="px-3 py-3 font-medium">{x}</th>)}</tr></thead><tbody className="divide-y divide-border">{sources.map((source, i) => <tr key={`${source.cve_id}-${i}`} className="text-slate-300 hover:bg-slate-800/40"><td className="px-3 py-3 font-mono text-blue-300">{cell(source.cve_id)}</td><td className="px-3 py-3">{joinedList(source.vendor, "—")}</td><td className="px-3 py-3">{joinedList(source.product, "—")}</td><td className="px-3 py-3">{cell(source.severity)}</td><td className="px-3 py-3">{cell(source.cvss_score)}</td><td className="px-3 py-3">{cell(source.source_type)}</td><td className="px-3 py-3 whitespace-nowrap">{source.published_at ? new Date(source.published_at).toLocaleDateString() : "—"}</td><td className="px-3 py-3">{cell(source.patch_status)}</td></tr>)}</tbody></table></div> }
export function AssistantResponse({ response }: { response: ChatResponse }) {
  const answer = response.answer ?? {}; const cves = (answer.priority_ranked_cves?.length ? answer.priority_ranked_cves : response.sources) as RankedCve[]; const actions = answer.recommended_actions ?? [];
  return <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .25 }} className="flex gap-3"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-blue-500/15 text-blue-300"><Bot className="h-4 w-4" /></div><div className="min-w-0 flex-1 space-y-4"><div className="pt-1 text-sm font-semibold">CyberRAG Assistant</div>
    {answer.query_summary && <section className="rounded-xl border border-border bg-card p-4"><div className="mb-2 flex items-center gap-2 text-sm font-semibold"><Sparkles className="h-4 w-4 text-blue-400" />Query summary</div><p className="text-sm leading-6 text-slate-400">{answer.query_summary}</p></section>}
    {cves.length > 0 && <section><h3 className="mb-3 text-sm font-semibold text-slate-200">Priority ranked CVEs <span className="text-slate-500">({cves.length})</span></h3><div className="space-y-3">{cves.map((cve, i) => <CveCard cve={cve} key={cve.cve_id ?? cve.id ?? i} />)}</div></section>}
    {actions.length > 0 && <section><h3 className="mb-3 text-sm font-semibold">Recommended actions</h3><div className="grid gap-2 sm:grid-cols-2">{actions.map((action, i) => <div key={i} className="flex gap-3 rounded-xl border border-border bg-card p-3 text-sm text-slate-300"><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-emerald-500/15 text-emerald-400"><Check className="h-3 w-3" /></span>{action}</div>)}</div></section>}
    {answer.cross_cve_patterns && <section className="rounded-xl border border-blue-500/20 bg-blue-500/[.06] p-4"><div className="mb-2 flex items-center gap-2 text-sm font-semibold text-blue-200"><FileText className="h-4 w-4" />Cross-CVE patterns</div><p className="text-sm leading-6 text-slate-400">{answer.cross_cve_patterns}</p></section>}
    <section><h3 className="mb-3 text-sm font-semibold">Hallucination flags</h3>{!answer.hallucination_flags?.length ? <Badge tone="green">No hallucination warnings</Badge> : <div className="space-y-2">{answer.hallucination_flags.map((flag, i) => <div key={i} className="flex gap-2 rounded-lg border border-amber-500/20 bg-amber-500/[.06] p-3 text-sm text-amber-200"><AlertTriangle className="h-4 w-4 shrink-0" />{flag}</div>)}</div>}</section>
    {response.sources.length > 0 && <section><h3 className="mb-3 flex items-center gap-2 text-sm font-semibold">Sources <Badge tone="slate">{response.sources.length} records</Badge></h3><SourcesTable sources={response.sources} /></section>}
  </div></motion.div>;
}
