import { useState } from "react";
import { ChevronDown, Clock3, ShieldAlert } from "lucide-react";
import type { RankedCve } from "../../types/chat";
import { Badge } from "../ui/badge";
import { joinedList } from "../../utils/format";
const toneFor = (value?: string) => value?.toLowerCase().includes("critical") ? "red" : value?.toLowerCase().includes("high") ? "amber" : "blue";
export function CveCard({ cve }: { cve: RankedCve }) {
  const [open, setOpen] = useState(false); const id = cve.cve_id ?? cve.id ?? "CVE record";
  return <div className="rounded-xl border border-border bg-card p-4 shadow-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-sm font-bold text-blue-300">{id}</p><h4 className="mt-1 font-medium text-slate-100">{cve.title ?? "Vulnerability intelligence record"}</h4><p className="mt-1 text-xs text-slate-500">{joinedList(cve.vendor, "Unknown vendor")} · {joinedList(cve.product, "Unknown product")}</p></div><div className="flex flex-wrap justify-end gap-1.5"><Badge tone={toneFor(cve.severity)}>{cve.severity ?? "Unknown"}</Badge>{cve.priority && <Badge tone="red">{cve.priority} priority</Badge>}<Badge tone={cve.source_type?.toLowerCase().includes("kev") ? "amber" : "slate"}>{cve.source_type ?? "NVD"}</Badge></div></div><div className="mt-4 flex flex-wrap gap-4 border-t border-border pt-3 text-xs text-slate-400"><span>Patch: <b className="text-slate-200">{cve.patch_status ?? "Review required"}</b></span>{typeof cve.days_overdue === "number" && <span className="inline-flex items-center gap-1 text-amber-300"><Clock3 className="h-3.5 w-3.5" />{cve.days_overdue} days overdue</span>}</div>{(cve.impact || cve.attacker_requirements || cve.priority_reason) && <><button onClick={() => setOpen(!open)} className="mt-3 flex items-center gap-1 text-xs font-medium text-blue-300 hover:text-blue-200">Details <ChevronDown className={"h-3.5 w-3.5 transition " + (open ? "rotate-180" : "")} /></button>{open && <div className="mt-3 grid gap-2 border-t border-border pt-3 text-sm text-slate-400">{cve.impact && <p><b className="text-slate-200">Impact: </b>{cve.impact}</p>}{cve.attacker_requirements && <p><b className="text-slate-200">Attacker requirements: </b>{cve.attacker_requirements}</p>}{cve.priority_reason && <p><b className="text-slate-200">Priority reason: </b>{cve.priority_reason}</p>}</div>}</>}</div>;
}
